version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: telegram_bot_postgres
    restart: always
    environment:
      POSTGRES_USER: telegram_bot_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: telegram_bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
